const COMPLETE_ARMOR_LIST= [
  {
    name: "Leather Legs",
    type: Leg,
    value: 2,
    desc:"Low damege protection",
    icon:"<",
    damageresist:.04 ,
  },
  {
  name: "ChainMail Legs",
    type: Leg,
    value: 5,
    desc:"higher damege protection then Leather",
    icon:"<",
      damageresist:.14,
  },
  {
    name: "Copper Legs",
  type: Leg,
  value: 10,
  desc:"higher damege protection then ChainMail",
  icon:"<",
    damageresist:.24,
},
{
  name: "Bronze Legs",
type: Leg,
value: 15,
desc:"higher damege protection then Copper",
icon:"<",
  damageresist:.34,
},
{
  name: "Iron Legs",
type: Leg,
value: 20,
desc:"higher damege protection then Bronze",
icon:"<",
  damageresist:.44,
},
{
  name: "Steel Legs",
type: Leg,
value: 25,
desc:"higher damege protection then Iron",
icon:"<",
  damageresist:.54,
},
{
  name: "Silver Legs",
type: Leg,
value: 33,
desc:"higher damege protection then Steel",
icon:"<",
  damageresist:.64,
},
{
  name: "Platinum Legs",
type: Leg,
value: 42,
desc:"Max damege protection",
icon:"<",
  damageresist:.74,
}
]
