const COMPLETE_HEAD_ARMOR_LIST = [
  { name: "Leather Hat",
    type: Item,
    value: 3,
    desc: "A simple hat for the early days",
    icon: "^",
    damageresist: .06,
  },
  { name: "Chain Mail Helmet",
    type: Item,
    value: 7,
    desc: "A strong but light armor that gives slight protection",
    icon: "^",
    damageresist: .16
  },
  { name: "Copper Helmet",
    type: Item,
    value: 7,
    desc: "A good helmet that will serve you well",
    icon: "^",
    damageresist: .26
  },
  { name: "Bronze Helmet",
    type: Item,
    value: 7,
    desc: "Better than Copper",
    icon: "^",
    damageresist: .36
  },
  { name: "Iron Helmet",
    type: Item,
    value: 7,
    desc: "A good quality helmet that will protect your head from arrows",
    icon: "^",
    damageresist: .46
  },
  { name: "Steel Helmet",
    type: Item,
    value: 7,
    desc: "Even better at not letting you die",
    icon: "^",
    damageresist: .56
  },
  { name: "Silver Helmet",
    type: Item,
    value: 7,
    desc: "Almost the best",
    icon: "^",
    damageresist: .36
  },
  { name: "Platinum Helmet",
    type: Item,
    value: 7,
    desc: "The best of the best",
    icon: "^",
    damageresist: .36
  }
]
